config/routes.rb
Rails.application.routes.draw do
  root to: "flats#index"
  get "flats/:id", to: "flats#show", as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  FLATS_URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"

  # DRY, Don't Repeat Yourself! This method will execute before each action in this controller
  before_action :set_flats

  # index -> display all the records
  def index; end

  # show -> display one record
  def show
    @flat = @flats.select { |flat| flat["id"] == params[:id].to_i }.first # params[:something] is always a string! Here we need to turn it into an integer
  end

  private

  # Keep private all your methods without a view (in fact they're call `methods`, not `actions`!)
  def set_flats
    response = open(FLATS_URL)
    @flats = JSON.parse(response.read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4 my-4">
        <div class="card">
          <img src="<%= flat['imageUrl'] %>" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= flat['name'] %></h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates quidem ipsum labore blanditiis, mollitia quae corporis distinctio esse dicta nemo culpa, pariatur itaque omnis nisi, harum doloribus perspiciatis suscipit natus!</p>
            <%= link_to "See flat", flat_path(flat['id']), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<img src="<%= @flat['imageUrl'] %>" class="img-fluid" alt="Responsive image" style="height: 400px; width: 100%; object-fit: cover;">

<h1><%= @flat["name"] %></h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit, eos pariatur, harum repellendus aliquid deserunt accusamus, aut id, dignissimos distinctio perspiciatis iste repellat quas eum at itaque ut iusto. Eveniet?</p>

<p><strong>Price:</strong> <%= @flat["price"] %>€</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <%= link_to "Static Airbnb", root_path, class: "navbar-brand" %>
      <!-- Produces <a class="navbar-brand" href="/">Static Airbnb</a> -->
    </nav>

    <%= yield %>
  </body>
</html>